# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build_docs:
    name: "Build Javadocs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Docs with Gradle
        run: ./gradlew dokkaJavadoc
      - uses: crazy-max/ghaction-github-pages@v2.0.0
        with:
          keep_history: true
          allow_empty_commit: true
          build_dir: build/docs/javadoc/-backpacks
        
