- name: GitHub Pages
  uses: crazy-max/ghaction-github-pages@v2.0.0
  with:
    keep_history: true
    # Allow an empty commit to be created
    allow_empty_commit: true # optional, default is true
    # Build directory to deploy
    build_dir: build/docs/javadoc/-backpacks
